### ISSUE TITLE
Problem with berserk?

### ISSUE THREAD

**Issue by 9acca9** [Cqsi/lichs#21]
Hi.
Im having this error. I install like this "pip3 install lichs".
Im running this on a raspberry pi zero w.

After put the token, im getting this:

```
pi@chess:~/.local/bin $ python3 lichs
Traceback (most recent call last):
  File "lichs", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/lichs/__main__.py", line 34, in main
    account_data = client.account.get()
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/clients.py", line 115, in get
    return self._r.get(path, converter=models.Account.convert)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/session.py", line 60, in get
    return self.request('GET', *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/session.py", line 56, in request
    return fmt.handle(response, is_stream=is_stream, converter=converter)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/formats.py", line 35, in handle
    return converter(self.parse(response))
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/formats.py", line 76, in parse
    return response.json(cls=self.decoder)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 535, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
Thanks.

**Comment by Cqsi** [comment]
I'll look into this tomorrow.

**Comment by 9acca9** [comment]
> I'll look into this tomorrow.

ok, thanks.
It seems is something related to SimpleJson (i uninstall this and now is working). I have this preinstalled on Raspbian.
Somebody talk about this on the github of berserk (me also).

**Comment by Cqsi** [comment]
Yeah, I can't get error on my computer, but it seems to be linked to SimpleJson. Good if you got it to work.

**Comment by Cqsi** [comment]
Shall I close this issue?

**Comment by 9acca9** [comment]
@Cqsi Yes. Thanks!
Im using your code with my physical chess board. (i have to change some things still, but is amazing)
thanks for share your work!!!!!!!!!!!!!!

**Comment by Cqsi** [comment]
Wow! So can you play against real players on Lichess using your physical board? That sounds amazing!

**Comment by 9acca9** [comment]
@Cqsi Yes! you made me happy!
